language: php
sudo: false

php:
  - 7.1
  - 7.2

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpdoc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: master
