language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0.3
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION = 5.5 ]] ; then echo yes | pecl install apcu-4.0.10; fi;
  - if [[ $TRAVIS_PHP_VERSION = 7.0.3 ]] ; then echo yes | pecl install apcu; fi;
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add ./tests/apc.ini; fi;
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpdoc

after_script:
  - CODECLIMATE_REPO_TOKEN=4c4f78edc9de922f7745810a2618ac6ccaa7528271a75c646e458d4380ef6c40 vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./docs
  on:
    branch: master
